data_ops_bigquery:
  target: "{{ env_var('DBT_PROFILE_TARGET', 'dev') }}"
  outputs:
    dev:
      dataset: ltf_data_lake_hml
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: us-central1
      method: oauth
      priority: interactive
      project: learntofly-180002
      threads: 1
      type: bigquery
    hml:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GCP_KEY_JSON_PATH') }}"
      project: learntofly-180002
      location: us-central1
      dataset: ltf_data_lake_hml
      priority: batch
      threads: 1
    main:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GCP_KEY_JSON_PATH') }}"
      project: learntofly-180002
      location: us-central1
      dataset: ltf_data_lake_prd
      priority: batch
      threads: 1
