name: Run dbt on BigQuery

on:
  push:
    branches:
      - main
      - hml
  workflow_dispatch:

env:
  DBT_PROFILES_DIR: ./

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create GCP credentials file
      run: |
        echo "${{ secrets.GCP_CREDS }}" | base64 --decode > /tmp/gcp_credentials.json

    - name: Run dbt
      uses: docker://fishtownanalytics/dbt:latest
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp_credentials.json
        DBT_PROFILES_DIR: ./
      run: |
        dbt run --profiles-dir .
