# .github/workflows/dbt.yml
name: Run dbt on BigQuery

on:
  push:
    branches:
      - main
      - hml
  workflow_dispatch:

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create GCP credentials file
      run: |
        echo "${{ secrets.GCP_CREDS }}" > /tmp/gcp_credentials.json

    - name: Configure dbt profile
      run: |
        mkdir -p /home/runner/.dbt
        echo "$DBT_PROFILES_CONTENT" > /home/runner/.dbt/profiles.yml
      env:
        DBT_PROFILES_CONTENT: |
          data_ops_bigquery:
            target: dev
            outputs:
              dev:
                type: bigquery
                method: service-account
                project: learntofly-180002
                dataset: your_bigquery_dataset
                threads: 1
                keyfile: /tmp/gcp_credentials.json
                timeout_seconds: 300
                location: us-central1
                priority: interactive

    - name: Run dbt
      run: |
        dbt run
      env:
        DBT_PROFILES_DIR: /home/runner/.dbt
