# .github/workflows/dbt.yml
name: Run dbt on BigQuery

on:
  push:
    branches:
      - main
      - hml
  workflow_dispatch:

env:
  DBT_PROFILES_DIR: ./
  DBT_PROFILE_TARGET: hml
jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create GCP credentials file
      run: |
        echo "${{ secrets.GCP_CREDS }}" > /tmp/gcp_credentials.json

    - name: Run dbt
      run: |
        export GCP_KEY_JSON_PATH=/tmp/gcp_credentials.json
        dbt run
      env:
        DBT_PROFILES_DIR: /home/runner/.dbt
