# .github/workflows/dbt.yml
name: Run dbt on BigQuery

on:
  push:
    branches:
      - main
      - hml
  workflow_dispatch:

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure dbt profile
      run: |
        mkdir -p ~/.dbt
        echo "$DBT_PROFILES_CONTENT" > ~/.dbt/profiles.yml
      env:
        DBT_PROFILES_CONTENT: |
          default:
            target: dev
            outputs:
              dev:
                type: bigquery
                method: service-account
                project: learntofly-180002
                threads: 1
                keyfile: /github/workspace/service-account-file.json
                timeout_seconds: 300
                location: us-central1
                priority: interactive

    - name: Run dbt
      run: |
        dbt run
      env:
        DBT_PROFILES_DIR: ~/.dbt
        GOOGLE_APPLICATION_CREDENTIALS: /github/workspace/service-account-file.json
        DBT_PROFILES_CONTENT: ${{ secrets.GCP_CREDS }}
